language: php

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --no-interaction

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial

script:
  - vendor/bin/phpunit
